# Generated by Django 5.2 on 2025-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_book_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
